Implemented first batch of controllers
blueOceanOne/PuppyMates pull request #11
Opened 2022-11-25 23:26 UTC by KateFeaster

Controllers still need some work (as discussed with the team), but this gives us a starting off point to test with.

2022-11-25 23:32 UTC, boyiq requested changes
Thank you Kate and Taylor for working on the controllers! Everything looks good except just need to add error handling to these controller functions.

2022-11-25 23:32 UTC, boyiq commented on backend/server/controllers.js
>      }).then((result) => {
Add .catch() to log error and send error code back in res.

2022-11-25 23:46 UTC, boyiq approved these changes

2022-11-26 07:00 UTC, avaboonzaayer approved these changes
looks good to me! nice work guys

2022-11-26 18:28 UTC, merged